"""Product help for additive audio nodes, isolated from legacy tooltip changes."""
AUDIO_TOOLTIPS = {
    "AudioArtifactReduction": {
        "audio": "Music to inspect; batch, channels, sample rate and full duration are preserved.",
        "enabled": "Off passes the original audio unchanged without spectral analysis. Independent of Refinement and Mastering.",
        "mode": "Reduce attenuates spectral outliers. Analyze only reports candidates and passes audio unchanged; removed_audio is silence.",
        "sensitivity": "Gentle needs strong frequency AND time contrast. Strong finds more candidates but can affect legitimate notes. Not an AI-origin detector.",
        "min_frequency_hz": "Lower edge of the detection/reduction band; default 3 kHz protects bass and much of the vocal body.",
        "max_frequency_hz": "Upper edge, limited to 45% of the actual sample rate. Both edges have soft transitions.",
        "max_reduction_db": "Maximum spectral-bin attenuation before wet/dry mixing. Start at 3 dB; no gain or replacement synthesis is added.",
        "protect_transients": "Reduce intervention around detected broadband attacks, helping preserve percussion. Cannot guarantee preservation of every instrument.",
        "mix": "Wet/dry strength. Zero returns original audio. Listen to removed_audio to judge what the node is taking away.",
    },
    "MiniMaxParametricEQ": {
        "audio": "Audio to equalize. All batch items/channels are preserved; processing uses the CPU.",
        "eq_settings_json": "Versioned EQ settings. Edit using the curve/table or connect Auto-EQ's proposal. Batch proposals must match the audio batch.",
        "bypass": "Return the input unchanged; no gain, filtering or normalization.",
    },
    "MiniMaxAutoEQAnalyze": {
        "enabled": "Off skips analysis and emits unity settings; manual EQ in the optimized workflows stays independent.",
        "audio": "Source audio to analyze. This node proposes filters without processing the audio.",
        "target_mode": "Reference matches broad tonal balance. Warm/Bright tilt are creative choices, not an ideal mastering standard.",
        "reference_audio": "Reference track: one item for all sources, or one reference per source batch item. If missing in Reference mode, warns and returns unity EQ so production can continue; choose Warm/Bright for correction without a reference.",
        "strength_percent": "Fraction of the broad tonal difference to correct. Start at 50% and audition.",
        "max_gain_db": "Limits individual gains and the predicted combined curve. Start at 3 dB.",
        "max_bands": "Maximum number of broad parametric bands the analysis may propose, up to six.",
        "min_frequency_hz": "Lower correction boundary. Frequencies without reliable evidence are excluded.",
        "max_frequency_hz": "Upper correction boundary, also limited by source/reference sample rates.",
    },
    "MiniMaxMasteringCompressor": {
        "audio": "Mono/stereo AUDIO; each batch item gets independent dynamics and loudness analysis.",
        "bypass": "Return the original audio without resampling or FFmpeg metering.",
        "target_lufs": "Integrated loudness goal, not compressor threshold. The report explains when limits prevent reaching it.",
        "ceiling_dbtp": "Final measured true-peak ceiling. Leave headroom for later lossy encoding.",
        "target_sample_rate": "Resample before dynamics so limiting and final measurement use the actual output rate.",
        "compressor_enabled": "Disable compression while keeping input gain, loudness targeting and limiting active.",
        "threshold_db": "Detector level above which compression begins; adjust to the source level.",
        "ratio": "Compression ratio. 1 is unity compression; 1.5–2 is a gentle starting point.",
        "knee_db": "Width of the smooth transition around threshold; zero is a hard knee.",
        "attack_ms": "Gain-reduction attack time constant. The detector uses 1 ms control cells.",
        "release_ms": "Compressor recovery time constant, independent of limiter release.",
        "sidechain_hz": "Highpass in the detector only. Zero disables it; the audible bass is not filtered.",
        "detector": "RMS detects energy; Peak detects the maximum across channels. Both link stereo gain.",
        "input_gain_db": "Explicit gain before the compressor. This changes how strongly it compresses.",
        "max_makeup_db": "Maximum positive gain allowed to approach the LUFS target; prevents boosting near-silence excessively.",
        "max_limiter_reduction_db": "Maximum intended limiter reduction. If more is needed, loudness is reduced instead of forcing the target.",
        "lookahead_ms": "Limiter anticipation window; output latency is compensated and length preserved.",
        "limiter_release_ms": "Time for a 12 dB linear recovery in the limiter. This is not compressor release.",
    },
}
