import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {applyMasteringPreset,restoreAppendedControls} from '../web/mastering_preset_utils.js';
const presets=JSON.parse(readFileSync(new URL('../web/mastering_presets.json',import.meta.url)));
const node={widgets:[{name:'ratio',value:9},{name:'bypass',value:true}]};
applyMasteringPreset(node,'Balanced - gentle glue',presets);
assert.equal(node.widgets[0].value,1.5);
assert.equal(node.widgets[1].value,true);
node.widgets[0].value=2.8;
applyMasteringPreset(node,'Custom',presets);
assert.equal(node.widgets[0].value,2.8);
const check={type:'MiniMaxModelAutodownload',widgets:[{name:'yue2_models',value:true}]};
restoreAppendedControls(check,{widgets_values:[true,true,true,true,true]});
assert.equal(check.widgets[0].value,false);
check.widgets[0].value=true;
restoreAppendedControls(check,{widgets_values:[true,true,true,true,true,true]});
assert.equal(check.widgets[0].value,true);
const settings={type:'MiniMaxMusicModelSettings',widgets:[{name:'max_duration',value:250},{name:'yue2_max_duration',value:360}]};
restoreAppendedControls(settings,{widgets_values:Array(18).fill(0)});
assert.equal(settings.widgets[1].value,250);
console.log('Mastering presets and appended-widget compatibility OK');
